import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { FaArrowLeft, FaGlobe, FaInfoCircle } from 'react-icons/fa';

const TermsAndConditions = () => {
    const navigate = useNavigate();
    const [language, setLanguage] = useState('en');

    // Scroll to top on language change
    useEffect(() => {
        window.scrollTo(0, 0);
    }, [language]);

    const termsData = {
        en: {
            title: "Terms of Use",
            lastUpdated: "Last Updated: December 2024",
            disclaimer: "Disclaimer: In case of any discrepancy or difference, the English version will take precedence over the translation.",
            intro: [
                "This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.",
                "This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name www.apkcrackers.com ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').",
                "The Platform is owned by APK Crackers Private Limited, a company incorporated under the Companies Act, 1956 with its registered office at Sivakasi, Tamil Nadu, India (hereinafter referred to as 'APK Crackers')."
            ],
            agreementText: "ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.",
            sections: [
                {
                    heading: "1. Membership Eligibility",
                    content: "Transaction on the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are 'incompetent to contract' within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Platform. If you are a minor i.e. under the age of 18 years, you may use the Platform or access content on the Platform only under the supervision and prior consent/permission of a parent or legal guardian. APK Crackers reserves the right to terminate your membership and/or refuse to provide you with access to the Platform if it is brought to APK Crackers' notice or if it is discovered that You are under the age of 18 years and transacting on the Platform."
                },
                {
                    heading: "2. Your Account and Registration Obligations",
                    content: "If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Platform and refuse to provide You with access to the Platform."
                },
                {
                    heading: "3. Communications",
                    content: "When You use the Platform or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise."
                },
                {
                    heading: "4. Charges",
                    content: "APK Crackers may charge a nominal fee for browsing and buying on the Platform. APK Crackers reserves the right to change its Fee Policy from time to time. In particular, APK Crackers may at its sole discretion introduce new services/fees and modify some or all of the existing services/fees offered on the Platform. Changes to the Fee Policy shall be posted on the Platform and such changes shall automatically become effective immediately after they are posted on the Platform."
                },
                {
                    heading: "5. Privacy Policy",
                    content: "We view protection of Your privacy as a very important principle. We understand clearly that You and Your Personal Information is one of Our most important assets. We store and process Your Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and Rules there under."
                },
                {
                    heading: "6. Order Policy",
                    content: "All orders placed on APK Crackers are subject to product availability and acceptance. We reserve the right to refuse or cancel any order for any reason, including limitations on quantities available for purchase, inaccuracies in product or pricing information, or problems identified by our fraud detection systems. Orders are processed only after payment confirmation. Once an order is placed, you will receive an order confirmation email. Delivery timelines are estimates and may vary based on location and product availability. APK Crackers is not responsible for delays caused by factors beyond our control."
                },
                {
                    heading: "7. Payment Policy",
                    content: "APK Crackers accepts various payment methods including Credit/Debit Cards, Net Banking, UPI, Digital Wallets, and Cash on Delivery (where available). All prices are listed in Indian Rupees (INR) and include applicable taxes unless otherwise stated. Payment information is processed securely through encrypted payment gateways. We do not store your complete card details on our servers. In case of payment failure, the amount will be refunded to your source account within 5-7 business days. For Cash on Delivery orders, payment must be made in cash to the delivery personnel at the time of delivery."
                },
                {
                    heading: "8. Shipping Policy",
                    content: "APK Crackers ships products across India through reliable courier partners. Shipping charges, if applicable, will be displayed at checkout before order confirmation. Standard delivery typically takes 5-7 business days, while express delivery (where available) takes 2-3 business days. Delivery times may vary based on location and product availability. We ship to the address provided during checkout - please ensure accuracy. Orders are tracked and you will receive tracking information via email/SMS. APK Crackers is not liable for delays caused by courier partners, natural disasters, or unforeseen circumstances. For high-value items, signature verification may be required at delivery."
                },
                {
                    heading: "9. Return Policy",
                    content: "APK Crackers offers a hassle-free return policy for most products. Returns are accepted within 7-30 days of delivery depending on the product category. To be eligible for return, products must be unused, in original packaging with all tags and accessories intact. Certain products like intimate wear, perishable goods, and personalized items are non-returnable for hygiene and safety reasons. To initiate a return, contact our customer support with your order details. Once approved, our courier partner will collect the product from your address. Refunds will be processed within 7-10 business days after quality check. Return shipping is free for defective/damaged products, but may be charged for other return reasons."
                },
                {
                    heading: "10. Refund Policy",
                    content: "Refunds are processed after successful return and quality verification of the product. The refund amount will be credited to your original payment method within 7-10 business days. For Cash on Delivery orders, refunds will be processed via bank transfer to your registered account. Shipping charges are non-refundable except in cases of defective/damaged products or wrong item delivery. Partial refunds may be issued if the product shows signs of use or damage not caused during shipping. In case of order cancellation before shipment, full refund will be processed within 5-7 business days. For prepaid orders, if delivery fails due to incorrect address or customer unavailability, refund will be processed after deducting applicable shipping charges."
                },
                {
                    heading: "11. Applicable Law & Jurisdiction",
                    content: "Terms of Use shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be exclusively in Sivakasi, Tamil Nadu. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of courts in Sivakasi, Tamil Nadu."
                },
                {
                    heading: "12. Limitation of Liability",
                    content: "IN NO EVENT SHALL APK CRACKERS BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THESE TERMS OF USE, EVEN IF USER HAS BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES. Our total liability for any claims under these terms shall not exceed the amount paid by you for the product or service in question."
                }
            ],
            grievance: {
                title: "Grievance Officer",
                text: "In accordance with Information Technology Act 2000 and rules made there under and the Consumer Protection (E-Commerce) Rules, 2020, the name and contact details of the Grievance Officer are provided below:",
                details: {
                    name: "Mr. Selvadhanush S",
                    role: "Designation: Grievance Officer",
                    company: "APK Crackers Private Limited",
                    address: "Sivakasi, Tamil Nadu, India, 626123",
                    email: "grievance.officer@apkcrackers.com",
                    phone: "+91 98765 43210",
                    time: "Time: Mon - Sat (9:00 - 18:00)"
                }
            }
        },
        ta: {
            title: "பயன்பாட்டு விதிமுறைகள்",
            lastUpdated: "கடைசியாக புதுப்பிக்கப்பட்டது: டிசம்பர் 2024",
            disclaimer: "மறுப்பு: ஏதேனும் முரண்பாடு அல்லது வேறுபாடு இருந்தால், மொழிபெயர்ப்பைக் காட்டிலும் ஆங்கிலப் பதிப்பே முன்னுரிமை பெறும்.",
            intro: [
                "இந்த ஆவணம் தகவல் தொழில்நுட்பச் சட்டம், 2000 மற்றும் அதன் கீழ் உள்ள விதிகளின் அடிப்படையில் ஒரு மின்னணு பதிவாகும். இந்த மின்னணு பதிவு கணினி அமைப்பால் உருவாக்கப்பட்டது மற்றும் இதற்கு எந்த உடல் அல்லது டிஜிட்டல் கையொப்பங்களும் தேவையில்லை.",
                "இந்த ஆவணம் தகவல் தொழில்நுட்ப (இடைத்தரகர்கள் வழிகாட்டுதல்கள்) விதிகள், 2011 இன் விதி 3 (1) இன் விதிகளின்படி வெளியிடப்படுகிறது. இது www.apkcrackers.com ('இணையதளம்') மற்றும் அதனுடன் தொடர்புடைய மொபைல் தளம் மற்றும் மொபைல் பயன்பாடு ('பிளாட்ஃபார்ம்') ஆகியவற்றை அணுகுவதற்கான அல்லது பயன்படுத்துவதற்கான விதிகள், விதிமுறைகள், தனியுரிமைக் கொள்கை மற்றும் பயன்பாட்டு விதிமுறைகளை வெளியிடுவதைக் கட்டாயமாக்குகிறது.",
                "இந்த பிளாட்ஃபார்ம் APK Crackers Private Limited நிறுவனத்திற்கு சொந்தமானது. இது 1956 ஆம் ஆண்டு நிறுவனங்கள் சட்டத்தின் கீழ் பதிவுசெய்யப்பட்ட அலுவலகத்தை சிவகாசி, தமிழ்நாடு, இந்தியா ஆகிய இடங்களில் கொண்டுள்ளது."
            ],
            agreementText: "தளத்தை அணுகுவது, உலாவுவது அல்லது பயன்படுத்துவது என்பது இந்த பயன்பாட்டு விதிமுறைகளின் கீழ் உள்ள அனைத்து விதிமுறைகள் மற்றும் நிபந்தனைகளுக்கு உங்கள் ஒப்புதலைக் குறிக்கிறது, எனவே தொடர்வதற்கு முன் பயன்பாட்டு விதிமுறைகளை கவனமாகப் படிக்கவும்.",
            sections: [
                {
                    heading: "1. உறுப்பினர் தகுதி",
                    content: "இந்திய ஒப்பந்தச் சட்டம், 1872 இன் கீழ் சட்டரீதியாக பிணைக்கக்கூடிய ஒப்பந்தங்களை உருவாக்கக்கூடிய நபர்களுக்கு மட்டுமே பிளாட்ஃபார்மில் பரிவர்த்தனை கிடைக்கும். நீங்கள் 18 வயதுக்குட்பட்ட மைனராக இருந்தால், பெற்றோர் அல்லது சட்டப்பூர்வ பாதுகாவலரின் மேற்பார்வை மற்றும் முன் அனுமதியின் கீழ் மட்டுமே நீங்கள் பிளாட்ஃபார்மைப் பயன்படுத்தலாம். நீங்கள் 18 வயதுக்குட்பட்டவர் என்பது கண்டுபிடிக்கப்பட்டால், உங்கள் உறுப்பினரை நிறுத்தவும் அல்லது பிளாட்ஃபார்மிற்கான அணுகலை மறுக்கவும் APK Crackers-க்கு உரிமை உண்டு."
                },
                {
                    heading: "2. உங்கள் கணக்கு மற்றும் பதிவு கடமைகள்",
                    content: "நீங்கள் பிளாட்ஃபார்மைப் பயன்படுத்தினால், உங்கள் காட்சிப் பெயர் மற்றும் கடவுச்சொல்லின் ரகசியத்தன்மையைப் பேணுவதற்கு நீங்களே பொறுப்பாவீர்கள். மேலும் உங்கள் கணக்கின் கீழ் நடைபெறும் அனைத்து நடவடிக்கைகளுக்கும் நீங்களே பொறுப்பாவீர்கள். நீங்கள் வழங்கும் தகவல் தவறானது, துல்லியமற்றது அல்லது முழுமையற்றது என்று நாங்கள் சந்தேகித்தால், பிளாட்ஃபார்மில் உங்கள் அணுகலைத் தடுத்து நிறுத்த எங்களுக்கு உரிமை உண்டு."
                },
                {
                    heading: "3. தொடர்புகள்",
                    content: "நீங்கள் பிளாட்ஃபார்மைப் பயன்படுத்தும் போது அல்லது எங்களுக்கு மின்னஞ்சல்கள் அல்லது பிற தரவுகளை அனுப்பும்போது, ​​நீங்கள் மின்னணு பதிவுகள் மூலம் எங்களுடன் தொடர்பு கொள்கிறீர்கள் என்பதை ஒப்புக்கொள்கிறீர்கள். அவ்வப்போது தேவைப்படும்போது எங்களிடமிருந்து மின்னணு பதிவுகள் மூலம் தகவல்தொடர்புகளைப் பெற சம்மதிக்கிறீர்கள்."
                },
                {
                    heading: "4. கட்டணங்கள்",
                    content: "பிளாட்ஃபார்மில் உலாவுவதற்கும் வாங்குவதற்கும் APK Crackers பெயரளவு கட்டணத்தை வசூலிக்கலாம். அதன் கட்டணக் கொள்கையை அவ்வப்போது மாற்ற APK Crackers-க்கு உரிமை உண்டு. கட்டணக் கொள்கையில் மாற்றங்கள் பிளாட்ஃபார்மில் வெளியிடப்படும், மேலும் அவை வெளியிடப்பட்ட உடனேயே தானாகவே நடைமுறைக்கு வரும்."
                },
                {
                    heading: "5. தனியுரிமைக் கொள்கை",
                    content: "உங்கள் தனியுரிமையைப் பாதுகாப்பதை நாங்கள் மிக முக்கியமான கொள்கையாகக் கருதுகிறோம். நீங்களும் உங்கள் தனிப்பட்ட தகவல்களும் எங்களின் மிக முக்கியமான சொத்துக்களில் ஒன்று என்பதை நாங்கள் தெளிவாகப் புரிந்துகொள்கிறோம். தகவல் தொழில்நுட்பச் சட்டம், 2000 இன் படி, உங்கள் தகவல்களை நாங்கள் பாதுகாப்பான கணினிகளில் சேமித்து செயலாக்குகிறோம்."
                },
                {
                    heading: "6. ஆர்டர் கொள்கை",
                    content: "APK Crackers இல் வைக்கப்படும் அனைத்து ஆர்டர்களும் தயாரிப்பு கிடைக்கும் தன்மை மற்றும் ஏற்புக்கு உட்பட்டவை. எந்தவொரு காரணத்திற்காகவும் ஆர்டரை மறுக்க அல்லது ரத்து செய்ய எங்களுக்கு உரிமை உண்டு. கட்டண உறுதிப்படுத்தலுக்குப் பிறகு மட்டுமே ஆர்டர்கள் செயலாக்கப்படும். ஆர்டர் வைத்தவுடன், உறுதிப்படுத்தல் மின்னஞ்சலைப் பெறுவீர்கள். டெலிவரி நேரங்கள் மதிப்பீடுகள் மட்டுமே."
                },
                {
                    heading: "7. கட்டணக் கொள்கை",
                    content: "APK Crackers கிரெடிட்/டெபிட் கார்டுகள், நெட் பேங்கிங், UPI, டிஜிட்டல் வாலட்கள் மற்றும் கேஷ் ஆன் டெலிவரி உள்ளிட்ட பல்வேறு கட்டண முறைகளை ஏற்றுக்கொள்கிறது. அனைத்து விலைகளும் இந்திய ரூபாயில் (INR) பட்டியலிடப்பட்டுள்ளன. கட்டணத் தகவல் என்க்ரிப்ட் செய்யப்பட்ட கட்டண கேட்வேகள் மூலம் பாதுகாப்பாக செயலாக்கப்படுகிறது. கட்டணம் தோல்வியுற்றால், தொகை 5-7 வணிக நாட்களுக்குள் திரும்பப் பெறப்படும்."
                },
                {
                    heading: "8. ஷிப்பிங் கொள்கை",
                    content: "APK Crackers நம்பகமான கூரியர் பார்ட்னர்கள் மூலம் இந்தியா முழுவதும் தயாரிப்புகளை அனுப்புகிறது. ஷிப்பிங் கட்டணங்கள் செக்அவுட்டில் காண்பிக்கப்படும். நிலையான டெலிவரி பொதுவாக 5-7 வணிக நாட்கள் எடுக்கும். எக்ஸ்பிரஸ் டெலிவரி 2-3 வணிக நாட்கள் எடுக்கும். செக்அவுட்டின் போது வழங்கப்பட்ட முகவரிக்கு நாங்கள் அனுப்புகிறோம் - துல்லியத்தை உறுதிப்படுத்தவும். ட்ராக்கிங் தகவலை மின்னஞ்சல்/SMS மூலம் பெறுவீர்கள்."
                },
                {
                    heading: "9. திரும்பப் பெறும் கொள்கை",
                    content: "APK Crackers பெரும்பாலான தயாரிப்புகளுக்கு எளிதான திரும்பப் பெறும் கொள்கையை வழங்குகிறது. தயாரிப்பு வகையைப் பொறுத்து டெலிவரிக்குப் பிறகு 7-30 நாட்களுக்குள் திரும்பப் பெறுதல் ஏற்றுக்கொள்ளப்படும். திரும்பப் பெறுவதற்கு தகுதியுடையதாக இருக்க, தயாரிப்புகள் பயன்படுத்தப்படாமல், அசல் பேக்கேஜிங்குடன் இருக்க வேண்டும். திரும்பப் பெறுதலைத் தொடங்க, உங்கள் ஆர்டர் விவரங்களுடன் எங்கள் வாடிக்கையாளர் ஆதரவைத் தொடர்பு கொள்ளவும். தரச் சரிபார்ப்புக்குப் பிறகு 7-10 வணிக நாட்களுக்குள் பணத்தைத் திரும்பப் பெறுவீர்கள்."
                },
                {
                    heading: "10. பணத்தைத் திரும்பப்பெறும் கொள்கை",
                    content: "வெற்றிகரமான திரும்பப் பெறுதல் மற்றும் தயாரிப்பின் தரச் சரிபார்ப்புக்குப் பிறகு பணத்தைத் திரும்பப் பெறுதல் செயலாக்கப்படுகிறது. பணத்தைத் திரும்பப் பெறும் தொகை 7-10 வணிக நாட்களுக்குள் உங்கள் அசல் கட்டண முறைக்கு வரவு வைக்கப்படும். கேஷ் ஆன் டெலிவரி ஆர்டர்களுக்கு, பணத்தைத் திரும்பப் பெறுதல் உங்கள் பதிவு செய்யப்பட்ட கணக்கிற்கு வங்கி பரிமாற்றம் மூலம் செயலாக்கப்படும். ஷிப்பிங் கட்டணங்கள் திரும்பப் பெற முடியாது, குறைபாடுள்ள/சேதமடைந்த தயாரிப்புகள் அல்லது தவறான பொருள் டெலிவரி தவிர."
                },
                {
                    heading: "11. பொருந்தக்கூடிய சட்டம் மற்றும் அதிகார வரம்பு",
                    content: "பயன்பாட்டு விதிமுறைகள் இந்தியச் சட்டங்களின்படி நிர்வகிக்கப்படும் மற்றும் விளக்கப்படும். அதிகார வரம்பு சிவகாசி, தமிழ்நாடு மட்டுமே. இந்த விதிமுறைகள் தொடர்பாக எழும் எந்தவொரு சர்ச்சைகளும் சிவகாசி, தமிழ்நாட்டில் உள்ள நீதிமன்றங்களின் பிரத்யேக அதிகார வரம்புக்கு உட்பட்டவை."
                },
                {
                    heading: "12. பொறுப்பு வரம்பு",
                    content: "இந்த விதிமுறைகள் தொடர்பாக ஏற்படும் எந்தவொரு சிறப்பு, தற்செயலான, மறைமுக அல்லது விளைவு சேதங்களுக்கும் APK Crackers பொறுப்பேற்காது. இந்த விதிமுறைகளின் கீழ் எந்தவொரு உரிமைகோரலுக்கும் எங்கள் மொத்த பொறுப்பு நீங்கள் கேள்விக்குரிய தயாரிப்பு அல்லது சேவைக்கு செலுத்திய தொகையை மீறாது."
                }
            ],
            grievance: {
                title: "குறைதீர்க்கும் அதிகாரி",
                text: "தகவல் தொழில்நுட்பச் சட்டம் 2000 மற்றும் நுகர்வோர் பாதுகாப்பு (மின் வணிகம்) விதிகள், 2020 இன் படி, குறைதீர்க்கும் அதிகாரியின் விவரங்கள் கீழே உள்ளன:",
                details: {
                    name: "திரு. செல்வதனுஷ் எஸ்",
                    role: "பதவி: குறைதீர்க்கும் அதிகாரி",
                    company: "APK Crackers Private Limited",
                    address: "சிவகாசி, தமிழ்நாடு, இந்தியா, 626123",
                    email: "grievance.officer@apkcrackers.com",
                    phone: "+91 98765 43210",
                    time: "நேரம்: திங்கள் - சனி (9:00 - 18:00)"
                }
            }
        },
        hi: {
            title: "उपयोग की शर्तें",
            lastUpdated: "अंतिम अपडेट: दिसंबर 2024",
            disclaimer: "अस्वीकरण: किसी भी विसंगति या अंतर के मामले में, अंग्रेजी संस्करण अनुवाद पर हावी होगा।",
            intro: [
                "यह दस्तावेज़ सूचना प्रौद्योगिकी अधिनियम, 2000 और उसके तहत लागू नियमों के संदर्भ में एक इलेक्ट्रॉनिक रिकॉर्ड है। यह इलेक्ट्रॉनिक रिकॉर्ड कंप्यूटर सिस्टम द्वारा उत्पन्न होता है और इसके लिए किसी भौतिक या डिजिटल हस्ताक्षर की आवश्यकता नहीं होती है।",
                "यह दस्तावेज़ सूचना प्रौद्योगिकी (मध्यस्थ दिशानिर्देश) नियम, 2011 के नियम 3 (1) के प्रावधानों के अनुसार प्रकाशित किया गया है, जिसके लिए डोमेन नाम www.apkcrackers.com ('वेबसाइट') और संबंधित मोबाइल साइट और मोबाइल एप्लिकेशन ('प्लेटफ़ॉर्म') तक पहुंच या उपयोग के लिए नियमों और विनियमों, गोपनीयता नीति और उपयोग की शर्तों को प्रकाशित करने की आवश्यकता होती है।",
                "प्लेटफ़ॉर्म का स्वामित्व APK Crackers Private Limited के पास है, जो कंपनी अधिनियम, 1956 के तहत निगमित एक कंपनी है, जिसका पंजीकृत कार्यालय शिवकाशी, तमिलनाडु, भारत में है।"
            ],
            agreementText: "साइट तक पहुंचने, ब्राउज़ करने या अन्यथा उपयोग करने से यह संकेत मिलता है कि आप इन उपयोग की शर्तों के तहत सभी नियमों और शर्तों से सहमत हैं, इसलिए आगे बढ़ने से पहले कृपया उपयोग की शर्तों को ध्यान से पढ़ें।",
            sections: [
                {
                    heading: "1. सदस्यता पात्रता",
                    content: "प्लेटफ़ॉर्म पर लेनदेन केवल उन व्यक्तियों के लिए उपलब्ध है जो भारतीय अनुबंध अधिनियम, 1872 के तहत कानूनी रूप से बाध्यकारी अनुबंध बना सकते हैं। यदि आप 18 वर्ष से कम आयु के हैं, तो आप केवल माता-पिता या कानूनी अभिभावक की देखरेख और पूर्व सहमति से ही प्लेटफ़ॉर्म का उपयोग कर सकते हैं। APK Crackers को आपकी सदस्यता समाप्त करने का अधिकार सुरक्षित है यदि यह पता चलता है कि आप 18 वर्ष से कम आयु के हैं।"
                },
                {
                    heading: "2. आपका खाता और पंजीकरण दायित्व",
                    content: "यदि आप प्लेटफ़ॉर्म का उपयोग करते हैं, तो आप अपने डिस्प्ले नाम और पासवर्ड की गोपनीयता बनाए रखने के लिए जिम्मेदार होंगे। आप सहमत हैं कि यदि आप कोई ऐसी जानकारी प्रदान करते हैं जो असत्य, गलत, वर्तमान नहीं या अधूरी है, तो हमें प्लेटफ़ॉर्म पर आपकी सदस्यता को अनिश्चित काल के लिए निलंबित या समाप्त करने का अधिकार होगा।"
                },
                {
                    heading: "3. संचार",
                    content: "जब आप प्लेटफ़ॉर्म का उपयोग करते हैं या हमें ईमेल भेजते हैं, तो आप सहमत हैं कि आप हमारे साथ इलेक्ट्रॉनिक रिकॉर्ड के माध्यम से संवाद कर रहे हैं। आप समय-समय पर हमसे इलेक्ट्रॉनिक रिकॉर्ड के माध्यम से संचार प्राप्त करने के लिए अपनी सहमति देते हैं।"
                },
                {
                    heading: "4. शुल्क",
                    content: "APK Crackers प्लेटफ़ॉर्म पर ब्राउज़िंग और खरीदारी के लिए मामूली शुल्क ले सकता है। APK Crackers समय-समय पर अपनी शुल्क नीति को बदलने का अधिकार सुरक्षित रखता है। शुल्क नीति में परिवर्तन प्लेटफ़ॉर्म पर पोस्ट किए जाएंगे और ऐसे परिवर्तन पोस्ट किए जाने के तुरंत बाद स्वचालित रूप से प्रभावी हो जाएंगे।"
                },
                {
                    heading: "5. गोपनीयता नीति",
                    content: "हम आपकी गोपनीयता की सुरक्षा को एक बहुत ही महत्वपूर्ण सिद्धांत मानते हैं। हम स्पष्ट रूप से समझते हैं कि आप और आपकी व्यक्तिगत जानकारी हमारी सबसे महत्वपूर्ण संपत्तियों में से एक है। हम सूचना प्रौद्योगिकी अधिनियम, 2000 के अनुसार आपकी जानकारी को सुरक्षित कंप्यूटरों पर संग्रहीत और संसाधित करते हैं।"
                },
                {
                    heading: "6. ऑर्डर नीति",
                    content: "APK Crackers पर दिए गए सभी ऑर्डर उत्पाद की उपलब्धता और स्वीकृति के अधीन हैं। हम किसी भी कारण से किसी भी ऑर्डर को अस्वीकार या रद्द करने का अधिकार सुरक्षित रखते हैं। भुगतान की पुष्टि के बाद ही ऑर्डर संसाधित किए जाते हैं। ऑर्डर देने के बाद, आपको एक पुष्टिकरण ईमेल प्राप्त होगा। डिलीवरी समय अनुमान हैं और स्थान और उत्पाद की उपलब्धता के आधार पर भिन्न हो सकते हैं।"
                },
                {
                    heading: "7. भुगतान नीति",
                    content: "APK Crackers क्रेडिट/डेबिट कार्ड, नेट बैंकिंग, UPI, डिजिटल वॉलेट और कैश ऑन डिलीवरी सहित विभिन्न भुगतान विधियों को स्वीकार करता है। सभी कीमतें भारतीय रुपये (INR) में सूचीबद्ध हैं। भुगतान जानकारी एन्क्रिप्टेड भुगतान गेटवे के माध्यम से सुरक्षित रूप से संसाधित की जाती है। भुगतान विफल होने की स्थिति में, राशि 5-7 कार्य दिवसों के भीतर वापस कर दी जाएगी।"
                },
                {
                    heading: "8. शिपिंग नीति",
                    content: "APK Crackers विश्वसनीय कूरियर पार्टनर्स के माध्यम से पूरे भारत में उत्पाद भेजता है। शिपिंग शुल्क चेकआउट पर प्रदर्शित किया जाएगा। मानक डिलीवरी में आमतौर पर 5-7 कार्य दिवस लगते हैं। एक्सप्रेस डिलीवरी में 2-3 कार्य दिवस लगते हैं। हम चेकआउट के दौरान प्रदान किए गए पते पर भेजते हैं - कृपया सटीकता सुनिश्चित करें। आपको ईमेल/SMS के माध्यम से ट्रैकिंग जानकारी प्राप्त होगी।"
                },
                {
                    heading: "9. वापसी नीति",
                    content: "APK Crackers अधिकांश उत्पादों के लिए परेशानी मुक्त वापसी नीति प्रदान करता है। उत्पाद श्रेणी के आधार पर डिलीवरी के 7-30 दिनों के भीतर वापसी स्वीकार की जाती है। वापसी के लिए पात्र होने के लिए, उत्पाद अप्रयुक्त होने चाहिए, मूल पैकेजिंग के साथ। वापसी शुरू करने के लिए, अपने ऑर्डर विवरण के साथ हमारे ग्राहक सहायता से संपर्क करें। गुणवत्ता जांच के बाद 7-10 कार्य दिवसों के भीतर धनवापसी संसाधित की जाएगी।"
                },
                {
                    heading: "10. धनवापसी नीति",
                    content: "सफल वापसी और उत्पाद की गुणवत्ता सत्यापन के बाद धनवापसी संसाधित की जाती है। धनवापसी राशि 7-10 कार्य दिवसों के भीतर आपकी मूल भुगतान विधि में जमा की जाएगी। कैश ऑन डिलीवरी ऑर्डर के लिए, धनवापसी आपके पंजीकृत खाते में बैंक हस्तांतरण के माध्यम से संसाधित की जाएगी। शिपिंग शुल्क वापसी योग्य नहीं हैं, दोषपूर्ण/क्षतिग्रस्त उत्पादों या गलत आइटम डिलीवरी के मामलों को छोड़कर।"
                },
                {
                    heading: "11. लागू कानून और अधिकार क्षेत्र",
                    content: "उपयोग की शर्तें भारतीय कानूनों के अनुसार शासित और व्याख्या की जाएंगी। अधिकार क्षेत्र विशेष रूप से शिवकाशी, तमिलनाडु में होगा। इन शर्तों के संबंध में उत्पन्न होने वाले किसी भी विवाद शिवकाशी, तमिलनाडु में अदालतों के विशेष अधिकार क्षेत्र के अधीन होंगे।"
                },
                {
                    heading: "12. दायित्व की सीमा",
                    content: "APK Crackers किसी भी स्थिति में इन शर्तों के संबंध में किसी भी विशेष, आकस्मिक, अप्रत्यक्ष या परिणामी क्षति के लिए उत्तरदायी नहीं होगा। इन शर्तों के तहत किसी भी दावे के लिए हमारी कुल देयता उस राशि से अधिक नहीं होगी जो आपने प्रश्न में उत्पाद या सेवा के लिए भुगतान की है।"
                }
            ],
            grievance: {
                title: "शिकायत अधिकारी",
                text: "सूचना प्रौद्योगिकी अधिनियम 2000 और उपभोक्ता संरक्षण (ई-कॉमर्स) नियम, 2020 के अनुसार, शिकायत अधिकारी का विवरण नीचे दिया गया है:",
                details: {
                    name: "श्री सेलवधनुष एस",
                    role: "पद: शिकायत अधिकारी",
                    company: "APK Crackers Private Limited",
                    address: "शिवकाशी, तमिलनाडु, भारत, 626123",
                    email: "grievance.officer@apkcrackers.com",
                    phone: "+91 98765 43210",
                    time: "समय: सोम - शनि (9:00 - 18:00)"
                }
            }
        }
    };

    const currentData = termsData[language];

    return (
        <div className="min-h-screen bg-[#F1F3F6] font-sans">
            {/* Header - Fixed & Styled like Flipkart */}
            <header className="bg-blue-600 text-white shadow-md sticky top-0 z-50">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <button
                            onClick={() => navigate(-1)}
                            className="p-2 hover:bg-blue-700 rounded-full transition-colors focus:outline-none"
                            aria-label="Go back"
                        >
                            <FaArrowLeft className="w-5 h-5" />
                        </button>
                        <h1 className="text-lg md:text-xl font-medium tracking-wide truncate">
                            {currentData.title}
                        </h1>
                    </div>

                    <div className="flex items-center gap-2 bg-white bg-opacity-20 px-3 py-1.5 rounded text-sm hover:bg-opacity-30 transition-all cursor-pointer">
                        <FaGlobe className="text-white w-4 h-4" />
                        <select
                            value={language}
                            onChange={(e) => setLanguage(e.target.value)}
                            className="bg-transparent text-white font-medium outline-none cursor-pointer border-none focus:ring-0 appearance-none pr-4"
                            style={{ backgroundImage: 'none' }} // Remove default arrow for cleaner look
                        >
                            <option value="en" className="text-gray-900 bg-white py-1">English</option>
                            <option value="ta" className="text-gray-900 bg-white py-1">தமிழ் (Tamil)</option>
                            <option value="hi" className="text-gray-900 bg-white py-1">हिंदी (Hindi)</option>
                        </select>
                    </div>
                </div>
            </header>

            {/* Main Content */}
            <main className="max-w-6xl mx-auto px-2 sm:px-6 lg:px-8 py-6">
                <div className="bg-white rounded-sm shadow-sm p-6 md:p-10 border border-gray-100">

                    {/* Disclaimer Alert */}
                    <div className="flex items-start gap-3 p-4 mb-8 bg-yellow-50 border border-yellow-200 rounded text-sm text-gray-700">
                        <FaInfoCircle className="w-5 h-5 text-yellow-600 flex-shrink-0 mt-0.5" />
                        <p className="font-medium">
                            {currentData.disclaimer}
                        </p>
                    </div>

                    {/* Introduction */}
                    <div className="text-sm text-gray-600 mb-8 space-y-4 text-justify leading-relaxed">
                        {currentData.intro.map((paragraph, idx) => (
                            <p key={idx}>{paragraph}</p>
                        ))}
                        <p className="font-bold text-gray-800 mt-6 uppercase text-xs md:text-sm tracking-wide">
                            {currentData.agreementText}
                        </p>
                    </div>

                    <hr className="border-gray-200 my-8" />

                    {/* Dynamic Sections */}
                    {currentData.sections.map((section, index) => (
                        <div key={index} className="mb-8">
                            <h2 className="text-base md:text-lg font-bold text-gray-800 mb-3">
                                {section.heading}
                            </h2>
                            <p className="text-sm text-gray-600 leading-7 text-justify">
                                {section.content}
                            </p>
                        </div>
                    ))}

                    <hr className="border-gray-200 my-8" />

                    {/* Grievance Officer Section */}
                    <div className="mb-8">
                        <h2 className="text-base md:text-lg font-bold text-gray-800 mb-4">
                            {currentData.grievance.title}
                        </h2>
                        <p className="text-sm text-gray-600 mb-4">
                            {currentData.grievance.text}
                        </p>

                        <div className="bg-gray-50 border border-gray-200 p-5 rounded-md text-sm text-gray-700 w-full md:w-1/2">
                            <p className="font-bold text-gray-900 text-base mb-1">{currentData.grievance.details.name}</p>
                            <p className="mb-3 text-gray-500 font-medium">{currentData.grievance.details.role}</p>

                            <div className="space-y-1.5">
                                <p>{currentData.grievance.details.company}</p>
                                <p>{currentData.grievance.details.address}</p>
                                <div className="mt-3 pt-3 border-t border-gray-200">
                                    <p className="flex flex-col sm:flex-row sm:gap-2">
                                        <span className="font-semibold text-gray-900 w-20">Email:</span>
                                        <a href={`mailto:${currentData.grievance.details.email}`} className="text-blue-600 hover:underline break-all">
                                            {currentData.grievance.details.email}
                                        </a>
                                    </p>
                                    <p className="flex flex-col sm:flex-row sm:gap-2">
                                        <span className="font-semibold text-gray-900 w-20">Phone:</span>
                                        <span>{currentData.grievance.details.phone}</span>
                                    </p>
                                    <p className="flex flex-col sm:flex-row sm:gap-2">
                                        <span className="font-semibold text-gray-900 w-20">Hours:</span>
                                        <span>{currentData.grievance.details.time}</span>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Footer */}
                    <div className="border-t border-gray-200 pt-8 mt-8 text-center">
                        <p className="text-xs text-gray-400 font-medium">
                            {currentData.lastUpdated}
                        </p>
                        <p className="text-xs text-gray-400 mt-2">
                            © 2024 APK Crackers Private Limited. All Rights Reserved.
                        </p>
                    </div>

                </div>
            </main>
        </div>
    );
};

export default TermsAndConditions;